import {
  IsNotEmpty,
  IsOptional,
  IsString,
  IsUUID,
  MaxLength,
} from 'class-validator';

/**
 * ============================================================================
 * CreateCategoryDto
 * ============================================================================
 * Creates a new Platform Category.
 *
 * NOTE:
 * - Slug is NOT accepted from the client.
} from 'class-validator';

/**
 * ============================================================================
 * CreateCategoryDto
 * ============================================================================
 * Creates a new Platform Category.
 *
 * NOTE:
 * - Slug is NOT accepted from the client.
 * - Slug is generated by the backend.
 * - Parent validation (including circular dependency detection)
 *   is handled by CatalogService.
 * ============================================================================
 */

export class CreateCategoryDto {
  /**
   * Category Name
   * Example:
   * Indoor Plants
   */
  @IsString()
  @IsNotEmpty()
  @MaxLength(100)
  category_name!: string;

  /**
   * Optional Description
   */
  @IsOptional()
  @IsString()
  description?: string;

  /**
   * Parent Category
   *
   * Service validates:
   * - Parent exists
   * - No circular hierarchy
   */
  @IsOptional()
  @IsUUID()
  parent_id?: string;
}
